# Generated by Django 5.1.4 on 2026-03-29 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='choice_1_health_effect',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scene',
            name='choice_1_sanity_effect',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scene',
            name='choice_2_health_effect',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scene',
            name='choice_2_sanity_effect',
            field=models.IntegerField(default=0),
        ),
    ]
