# Generated by Django 5.1.4 on 2026-03-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_scene_choice_1_health_effect_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='given_item',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='required_item_for_choice_1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='required_item_for_choice_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
