# Generated by Django 5.1.4 on 2026-03-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0003_scene_given_item_scene_required_item_for_choice_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='is_timed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scene',
            name='time_limit',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='scene',
            name='timeout_health_effect',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scene',
            name='timeout_next_id',
            field=models.IntegerField(default=0),
        ),
    ]
