# Generated by Django 5.1.4 on 2026-03-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0004_scene_is_timed_scene_time_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='ambient_sound',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='timeout_sanity_effect',
            field=models.IntegerField(default=0),
        ),
    ]
